#!/bin/bash
## nicholas
## version 0.0.1 - initial
##################################################
SH2=~/bin/sh2
declare -x SH2
. ${SH2}/cecho.sh &>/dev/null
. ${SH2}/error.sh
error "true" # show errors
_date() { # override
  date
}
shopt -s expand_aliases
. ${SH2}/aliases/commands.sh
##################################################
nicholas-hello() {
  cecho green "hello"
}
nicholas-test() {
  cecho green testing
  cecho yellow "cecho: ok"
  false || {
    error "manual break" ${FUNCNAME} ${LINENO}
    # false # throw error
    # true  # continue
  }
  cecho yellow "assert error: ok "

  cecho green done
}
nicholas-cron() {
  cecho green "running cron job ..."
  /usr/local/bin/bash $( dirname ${0} )/test-git-cron.sh
  cecho green "done"
}
nicholas-show() {
  . $( dirname ${0} )/${FUNCNAME}.sh
}
nicholas() {
  local log
  log=~/var/log/nicholas-ci
  declare -x log
  test -d "${log}" || {
    mkdir -pv ${log}
  }
  commands
}
##################################################
if [ ! ]
then
 true
else
 exit 1 # wrong args
fi
##################################################
nicholas ${@}
##################################################
## generated by create-stub2.sh v0.1.1
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
