#!/bin/bash
## nicholas-show
## version 0.0.1 - initial
##################################################
nicholas-show-logs() {
  find var/log/$( basename $( dirname ${0} ) ) -mindepth 1 -maxdepth 1 -type f |
  xargs realpath

}
nicholas-show() {
  commands
}
##################################################
nicholas-show ${@}
##################################################
## generated by create-stub2.sh v0.1.1
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
