#!/bin/bash
## test-git-cron
## version 0.0.2 - initialize as alias
##################################################
shopt -s expand_aliases
alias bind-variables='
{
  local log
}
'
alias initialize='
  log="var/log/${FUNCNAME}"
  test -d "${log}" || {
    mkdir -pv "${log}"
  }
'
repos() {
 true # inherit
}
test-git-ssh() {
  (
    cd ${1}
    pwd
    git branch
    bash ~/$( dirname ${0} )/${FUNCNAME}.sh
  )
}
for-each-repo() { { local function_name ; function_name="${1}" ; }
  local repo
  for repo in $( repos )
  do
   ${function_name} ${repo}
  done
}
main() {
  {
    date
    for-each-repo test-git-ssh
  } | tee -a ${log}/log 2>> ${log}/error
}
test-git-cron() {
  test ! -f "${FUNCNAME}-config.sh" || {
    . ${FUNCNAME}-config.sh
  }
  bind-variables
  ## ToDo: lock
  initialize
  ## ToDo: log rotation
  main
  ## ToDo: unlock
}
##################################################
if [ ${#} -eq 0 ]
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-git-cron
##################################################
## generated by create-stub2.sh v0.1.1
## on
## see <https://github.com/temptemp3/sh2>
##################################################
