#!/bin/bash
## test-git-ssh
## version 0.0.1 - initial
##################################################
test-git-ssh() {
  GIT_SSH_COMMAND="ssh -i ~/.ssh/identities/$( basename $( pwd ) )/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
  git pull
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-git-ssh
##################################################
## generated by create-stub2.sh v0.1.1
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
