#!/bin/bash
## test-git-cron
## version 0.0.2 - initialize as alias
##################################################
. ${SH2}/cecho.sh &>/dev/null
shopt -s expand_aliases
alias bind-variables='
{
  local log
}
'
alias initialize='
  test "${log}" || { 
    log="var/log/${FUNCNAME}"
  }
  test -d "${log}" || {
    mkdir -pv "${log}"
  }
'
repos() {
 true # inherit
}
test-git-ssh() {
  (
    date
    cd ${1}
    pwd
    /usr/local/bin/git branch
    /usr/local/bin/bash $( dirname ${0} )/${FUNCNAME}.sh 
  ) > ${FUNCNAME}-response
  test ! "$( grep -e 'Updating' ${FUNCNAME}-response )" || {
    cat ${FUNCNAME}-response |
    tee -a ${log}/log 2>> ${log}/error
    cecho yellow "$( rm -v ${FUNCNAME}-response ) removed"
  }
}
for-each-repo() { { local function_name ; function_name="${1}" ; }
  local repo
  for repo in $( repos )
  do
   ${function_name} ${repo}
  done
}
main() {
  {
    for-each-repo test-git-ssh
  } 
}
test-git-cron() {
  test ! -f "$( dirname ${0} )/${FUNCNAME}-config.sh" || {
    . $( dirname ${0} )/${FUNCNAME}-config.sh
  }
  #bind-variables
  ## ToDo: lock
  initialize
  ## ToDo: log rotation
  main
  ## ToDo: unlock
}
##################################################
if [ ${#} -eq 0 ]
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-git-cron
##################################################
## generated by create-stub2.sh v0.1.1
## on
## see <https://github.com/temptemp3/sh2>
##################################################
